// locations/noosa.js

module.exports = {
    town: {
        slug: "noosa",
        name: "Noosa",
        region: "Sunshine Coast",
        center: { lat: -26.3968, lng: 153.0906 },
    },

    venues: [
        // -------------------------
        // Breweries / Beer
        // -------------------------
        {
            name: "Land & Sea",
            slug: "land-and-sea",
            category: "Brewery",
            icon: "/icons/craft_beer.png",
            lat: -26.408347,
            lng: 153.043329,
            coords_source: "address",
            coords_accuracy: "high",
            address: "19 Venture Drive, Noosaville QLD",
            is_active: true,
            best_for: ["beer", "afternoon", "lunch", "dinner"],
            known_for_bullets: [
                "Small-batch craft beers",
                "Relaxed brewery lunches",
                "Easy arvo sessions",
            ],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["casual", "lively"],
            venue_mobile_number: "+61413500710",
        },


        // -------------------------
        // Fast casual / lunch
        // -------------------------
        {
            name: "Noosa Burger Co.",
            slug: "noosa-burger-co",
            category: "Burger",
            icon: "/icons/burger.png",
            lat: -26.386480,
            lng: 153.087644,
            coords_source: "address",
            coords_accuracy: "high",
            address: "10 Hastings St, Noosa Heads QLD",
            is_active: true,
            best_for: ["lunch", "dinner"],
            known_for_bullets: [
                "Big burgers & loaded sides",
                "Fast casual feeds",
                "Easy takeaway option",
            ],
            service_speed: "fast",
            price_risk: "low",
            walk_in_friendliness: "high",
            formality_level: 0,
            vibe_tags: ["casual", "quick"],
        },

        {
            name: "Sushi Wave",
            slug: "sushi-wave",
            category: "Sushi",
            icon: "/icons/sushi.png",
            lat: -26.385901,
            lng: 153.087469,
            coords_source: "address",
            coords_accuracy: "high",
            address: "5 Hastings St, Noosa Heads QLD",
            is_active: true,
            best_for: ["lunch", "dinner"],
            known_for_bullets: [
                "Fresh sushi rolls",
                "Quick lunch bites",
                "Light Japanese options",
            ],
            service_speed: "fast",
            price_risk: "low",
            walk_in_friendliness: "high",
            formality_level: 0,
            vibe_tags: ["casual", "quick"],
        },



        // -------------------------
        // Cafés / coffee / breakfast
        // -------------------------
        {
            name: "Noosa Coffee Roastery (Noosa Heads)",
            slug: "noosa-coffee-roastery-noosa-heads",
            category: "Cafe",
            icon: "/icons/coffee.png",
            lat: -26.395814,
            lng: 153.089947,
            coords_source: "address",
            coords_accuracy: "high",
            address: "3/77 Noosa Dr, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["coffee", "breakfast"],
            known_for_bullets: [
                "Specialty coffee stop in Noosa Junction",
                "Good for a quick morning caffeine hit",
                "Beans + takeaway friendly",
            ],
            service_speed: "fast",
            price_risk: "low",
            walk_in_friendliness: "high",
            formality_level: 0,
            vibe_tags: ["quick", "locals"],
        },

        {
            name: "VanillaFood (Noosa Junction)",
            slug: "vanillafood-noosa-junction",
            category: "Cafe",
            icon: "/icons/coffee.png",
            lat: -26.397073,
            lng: 153.091226,
            address: "2/10 Lanyana Way, Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch"],
            known_for_bullets: [
                "Popular Junction breakfast & brunch",
                "Good coffee + café classics",
                "Reliable daytime option",
            ],
            service_speed: "medium",
            price_risk: "low",
            walk_in_friendliness: "high",
            formality_level: 0,
            vibe_tags: ["casual", "breakfast"],
        },

        {
            name: "Noosa Social Espresso & Wine Bar",
            slug: "noosa-social",
            category: "Cafe / Wine Bar",
            icon: "/icons/coffee.png",
            lat: -26.388142,
            lng: 153.092323,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Shop 2/62 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["coffee", "breakfast", "lunch", "afternoon"],
            known_for_bullets: [
                "Coffee by day on Hastings",
                "Good for a casual bite",
                "Easy meet-up spot",
            ],
            service_speed: "medium",
            price_risk: "medium",
            walk_in_friendliness: "high",
            formality_level: 1,
            vibe_tags: ["casual", "hastings"],
        },





        // -------------------------
        // Hastings restaurants (mid/fancy)
        // -------------------------
        {
            name: "Locale Noosa",
            slug: "locale-noosa",
            category: "Italian (Fine)",
            icon: "/icons/fancy_dinner.png",
            lat: -26.388142,
            lng: 153.092323,
            coords_source: "address",
            coords_accuracy: "high",
            address: "62 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["dinner", "fancy_dinner", "late_night"],
            known_for_bullets: [
                "Date-night Italian",
                "Wine-forward dining",
                "Often best booked for peak times",
            ],
            formality_level: 3,
            walk_in_friendliness: "low",
            service_speed: "slow",
            price_risk: "high",
            vibe_tags: ["date", "special-occasion", "wine"],
            booking_likely: true,
        },

        {
            name: "Sails",
            slug: "sails-noosa",
            category: "Seafood",
            icon: "/icons/fancy_dinner.png",
            lat: -26.387223,
            lng: 153.092425,
            coords_source: "address",
            coords_accuracy: "high",
            address: "75 Hastings St, Noosa Heads QLD",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner"],
            known_for_bullets: [
                "Premium seafood",
                "Long lunches by the beach",
                "Special occasion meals",
            ],
            formality_level: 3,
            walk_in_friendliness: "low",
            service_speed: "slow",
            price_risk: "high",
            vibe_tags: ["views", "date", "special-occasion"],
            booking_likely: true,
        },

        {
            name: "Season Restaurant",
            slug: "season-restaurant-noosa",
            category: "Beachfront Dining",
            icon: "/icons/wine.png",
            lat: -26.386089,
            lng: 153.088923,
            coords_source: "address",
            coords_accuracy: "high",
            address: "25 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "lunch", "dinner"],
            known_for_bullets: [
                "Beachfront all-day dining",
                "Good for breakfast through dinner",
                "Easy stop after the beach",
            ],
            formality_level: 2,
            walk_in_friendliness: "medium",
            service_speed: "medium",
            price_risk: "high",
            vibe_tags: ["views", "casual"],
        },





        // -------------------------
        // Clubs / casual views
        // -------------------------
        {
            name: "Noosa Surf Club",
            slug: "noosa-surf-club",
            category: "Surf Club",
            icon: "/icons/fish_chips.png",
            lat: -26.387154,
            lng: 153.092029,
            coords_source: "address",
            coords_accuracy: "high",
            address: "69 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "afternoon", "dinner", "beer"],
            known_for_bullets: [
                "Beachfront club meals",
                "Great views over Main Beach",
                "Easy walk-in dining",
            ],
            formality_level: 0,
            walk_in_friendliness: "high",
            price_risk: "low",
            vibe_tags: ["views", "casual", "family"],
        },

        {
            name: "Sunshine Beach Surf Club",
            slug: "sunshine-beach-surf-club",
            category: "Surf Club",
            icon: "/icons/fish_chips.png",
            lat: -26.404928,
            lng: 153.108437,
            address: "Corner of Duke St & Belmore Terrace, Sunshine Beach QLD 4567",
            is_active: true,
            best_for: ["lunch", "afternoon", "dinner", "beer"],
            known_for_bullets: [
                "Big ocean views",
                "Classic club meals & drinks",
                "Great casual sunset stop",
            ],
            formality_level: 0,
            walk_in_friendliness: "high",
            price_risk: "low",
            vibe_tags: ["views", "casual", "family", "locals"],
        },

        // -------------------------
        // Noosa Junction nightlife
        // -------------------------
        {
            name: "Miss Moneypenny's",
            slug: "miss-moneypennys",
            category: "Cocktail Bar",
            icon: "/icons/wine.png",
            lat: -26.386718,
            lng: 153.087370,
            coords_source: "address",
            coords_accuracy: "high",
            address: "6 Hastings St, Noosa Heads QLD",
            is_active: true,
            best_for: ["afternoon", "dinner", "late_night"],
            known_for_bullets: [
                "Cocktails & late-night energy",
                "Bar snacks",
                "Good pre/post-dinner stop",
            ],
            formality_level: 1,
            walk_in_friendliness: "medium",
            service_speed: "medium",
            price_risk: "high",
            vibe_tags: ["lively", "cocktails"],
        },

        {
            name: "Village Bicycle",
            slug: "village-bicycle",
            category: "Bar & Grill",
            icon: "/icons/craft_beer.png",
            lat: -26.397222,
            lng: 153.090444,
            address: "6/16 Sunshine Beach Rd, Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["beer", "drinks", "afternoon", "late_night"],
            known_for_bullets: [
                "Great tap selection",
                "Burgers that hit the spot",
                "Easy casual vibe",
            ],
            formality_level: 1,
            walk_in_friendliness: "high",
            price_risk: "medium",
            vibe_tags: ["casual", "lively", "beer garden"],
        },

        {
            name: "Mr Drifter",
            slug: "mr-drifter",
            category: "Modern Bar",
            icon: "/icons/beer.png",
            lat: -26.396517,
            lng: 153.090310,
            address: "G13/18-22 Sunshine Beach Rd, Noosa Junction QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["dinner", "late_night", "drinks"],
            known_for_bullets: [
                "Kitchen-driven bar food",
                "Great vibe",
                "Regular live music nights",
            ],
            formality_level: 1,
            walk_in_friendliness: "medium",
            price_risk: "medium",
            vibe_tags: ["lively", "music"],
        },

        {
            name: "Sum Yung Guys",
            slug: "sum-yung-guys",
            category: "Asian Fusion",
            icon: "/icons/asian.png",
            lat: -26.404118,
            lng: 153.072430,
            coords_source: "address",
            coords_accuracy: "high",
            address: "205 Weyba Rd, Noosaville QLD",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: [
                "Share plates & bold flavours",
                "Busy dinner vibe",
                "Often worth booking",
            ],
            formality_level: 2,
            walk_in_friendliness: "low",
            price_risk: "medium",
            vibe_tags: ["lively", "date"],
            booking_likely: true,
        },

        {
            name: "Ricky's River Bar",
            slug: "rickys",
            category: "Modern",
            icon: "/icons/fancy_dinner.png",
            lat: -26.391655,
            lng: 153.078861,
            coords_source: "address",
            coords_accuracy: "high",
            address: "2 Quamby Pl, Noosa Heads QLD",
            is_active: true,
            best_for: ["afternoon", "dinner", "fancy_dinner"],
            known_for_bullets: ["Riverside dining", "Modern plates", "Cocktails at sunset"],
            formality_level: 2,
            walk_in_friendliness: "medium",
            price_risk: "high",
            vibe_tags: ["views", "date", "cocktails"],
            booking_likely: true,
        },

        {
            name: "Bistro C",
            slug: "bistro-c",
            category: "Beachside Bistro",
            icon: "/icons/fancy_dinner.png",
            lat: -26.386507,
            lng: 153.090567,
            coords_source: "address",
            coords_accuracy: "high",
            address: "49 Hastings St, Noosa Heads QLD",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner"],
            known_for_bullets: [
                "Beachside bistro classics",
                "Seafood & cocktails",
                "Great for sunset meals",
            ],
            formality_level: 2,
            walk_in_friendliness: "medium",
            price_risk: "high",
            vibe_tags: ["views", "date"],
            booking_likely: true,
        },
        {
            name: "Aromas Noosa",
            slug: "aromas-noosa",
            category: "Cafe & Bar",
            icon: "/icons/coffee.png",
            lat: -26.386951,
            lng: 153.090417,
            coords_source: "address",
            coords_accuracy: "high",
            address: "32 Hastings Street, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon"],
            known_for_bullets: ["All-day Hastings classic", "Coffee + breakfast plates", "Great people-watching spot"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["busy", "central", "casual"]
        },
        {
            name: "Rococo Bistro",
            slug: "rococo-bistro-noosa",
            category: "Italian",
            icon: "/icons/fancy_dinner.png",
            lat: -26.387123,
            lng: 153.090817,
            coords_source: "address",
            coords_accuracy: "high",
            address: "42 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner"],
            known_for_bullets: ["Italian mains + cocktails", "Alfresco dining vibe", "Feels like a ‘proper’ night out"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["date", "cocktails", "buzz"],
            booking_likely: true
        },
        {
            name: "Bang Bang Noosa",
            slug: "bang-bang-noosa",
            category: "Southeast Asian",
            icon: "/icons/asian.png",
            lat: -26.386951,
            lng: 153.090417,
            coords_source: "address",
            coords_accuracy: "high",
            address: "32 Hastings Street, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Big flavour Asian fusion", "Cocktails + ‘night out’ energy", "Best as a planned dinner"],
            price_risk: "high",
            walk_in_friendliness: "low",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["lively", "date", "cocktails"],
            booking_likely: true
        },
        {
            name: "MISSCHU (Bay Village Noosa)",
            slug: "misschu-noosa",
            category: "Asian Street Food",
            icon: "/icons/asian.png",
            lat: -26.387074,
            lng: 153.091652,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Bay Village Noosa, 27/18 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "dinner", "late_night"],
            known_for_bullets: ["Quick casual eats", "Dumplings + easy share plates", "Good when you don’t want ‘fine dining’"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "easy", "affordable"]
        },
        {
            name: "Café Le Monde",
            slug: "cafe-le-monde-noosa",
            category: "Cafe",
            icon: "/icons/coffee.png",
            lat: -26.387074,
            lng: 153.091652,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon"],
            known_for_bullets: ["Reliable all-day cafe", "Fast turnaround most days", "Easy fallback when everyone’s hungry"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "busy", "touristy"]
        },
        {
            name: "Providore on Hastings",
            slug: "providore-on-hastings",
            category: "Cafe & Deli",
            icon: "/icons/coffee.png",
            lat: -26.386945,
            lng: 153.092436,
            coords_source: "address",
            coords_accuracy: "high",
            address: "71 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch"],
            known_for_bullets: ["Grab-and-go + sit-down options", "Coffee + simple breakfast/lunch", "Good for quick ‘feed me now’ moments"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["quick", "casual", "central"]
        },
        {
            name: "Betty's Burgers (Noosa)",
            slug: "bettys-burgers-noosa",
            category: "Burger",
            icon: "/icons/burger.png",
            lat: -26.387074,
            lng: 153.091652,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "dinner", "late_night"],
            known_for_bullets: ["Fast burgers + shakes", "Great when you want simple + predictable", "Good with groups (everyone finds something)"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["quick", "casual", "family"]
        },
        {
            name: "El Capitano Pizzeria",
            slug: "el-capitano-noosa",
            category: "Pizza",
            icon: "/icons/italian.png",
            lat: -26.387074,
            lng: 153.091652,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Pizza that’s easy to share", "Good ‘no thinking’ dinner pick", "Works for couples or groups"],
            price_risk: "medium",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 0,
            vibe_tags: ["casual", "groups"]
        },
        {
            name: "Season Restaurant (Sofitel)",
            slug: "season-restaurant-sofitel-noosa",
            category: "Modern Australian",
            icon: "/icons/fancy_dinner.png",
            lat: -26.386315,
            lng: 153.088436,
            coords_source: "address",
            coords_accuracy: "high",
            address: "14–16 Hastings St (Sofitel), Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "lunch", "dinner", "fancy_dinner"],
            known_for_bullets: ["Hotel dining done properly", "Great if you want ‘easy nice’", "Good for special breakfasts too"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["polished", "date", "special-occasion"],
            booking_likely: true
        },
        {
            name: "Noosa Beach House Kitchen & Bar",
            slug: "noosa-beach-house-kitchen-bar",
            category: "Modern Australian",
            icon: "/icons/fancy_dinner.png",
            lat: -26.386315,
            lng: 153.088436,
            coords_source: "address",
            coords_accuracy: "high",
            address: "14–16 Hastings Street, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner", "late_night"],
            known_for_bullets: ["Polished dining on Hastings", "Cocktails + strong wine list", "Feels ‘premium’ without being stiff"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["date", "cocktails", "polished"],
            booking_likely: true
        },
        {
            name: "Massimo's Gelateria",
            slug: "massimos-gelateria-noosa",
            category: "Dessert",
            icon: "/icons/coffee.png",
            lat: -26.387074,
            lng: 153.091652,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["afternoon", "late_night"],
            known_for_bullets: ["Quick sweet treat", "Perfect post-dinner walk", "Good ‘everyone’s happy’ stop"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "family", "quick"]
        },
        {
            name: "Felix Espresso & Wine Bar",
            slug: "felix-espresso-wine-bar-noosa",
            category: "Cafe & Wine Bar",
            icon: "/icons/wine.png",
            lat: -26.388142,
            lng: 153.092323,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Shop 2, 62 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon"],
            known_for_bullets: ["Strong coffee + brunch", "Good ‘reset’ stop between beach and shopping", "Turns into a mellow wine vibe later"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["casual", "brunch", "wine"]
        },
        {
            name: "Raw & Rice (Hastings)",
            slug: "raw-and-rice-hastings-noosa",
            category: "Healthy / Poke",
            icon: "/icons/salad.png",
            lat: -26.387769,
            lng: 153.091835,
            coords_source: "address",
            coords_accuracy: "high",
            address: "2/52 Hastings St, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["lunch", "afternoon"],
            known_for_bullets: ["Fresh + light bowls", "Fast lunch when it’s hot", "Good ‘not-too-heavy’ option"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["healthy", "quick", "casual"]
        },

        // ---- NOOSA JUNCTION / SUNSHINE BEACH RD ----
        {
            name: "Light Years Asian Diner (Noosa)",
            slug: "light-years-asian-diner-noosa",
            category: "Asian",
            icon: "/icons/asian.png",
            lat: -26.396123,
            lng: 153.089887,
            address: "1 Sunshine Beach Rd, Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Busy, buzzy dinner spot", "Great for groups + sharing", "Strong ‘night out’ energy"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["lively", "groups", "share-plates"],
            booking_likely: true
        },
        {
            name: "Flo’s Crêperie",
            slug: "flos-creperie-noosa",
            category: "Cafe",
            icon: "/icons/coffee.png",
            lat: -26.397434,
            lng: 153.090768,
            address: "4/18 Sunshine Beach Rd, Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon"],
            known_for_bullets: ["Sweet + savoury crepes", "Easy casual breakfast", "Good ‘quick sit-down’ stop"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "quick", "family"]
        },
        {
            name: "Atelier Wine Bar",
            slug: "atelier-wine-bar-noosa",
            category: "Wine Bar",
            icon: "/icons/wine.png",
            lat: -26.397805,
            lng: 153.091274,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Noosa Junction (Sunshine Beach Rd), Noosa Heads QLD",
            is_active: true,
            best_for: ["afternoon", "dinner", "late_night"],
            known_for_bullets: ["Wine-first vibe", "Best for a relaxed ‘few glasses’ night", "Great for couples"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 2,
            vibe_tags: ["date", "wine", "chill"],
            booking_likely: false
        },
        {
            name: "4 Pines Brewing Co (Noosa)",
            slug: "4-pines-brewing-co-noosa",
            category: "Brewpub",
            icon: "/icons/craft_beer.png",
            lat: -26.396636,
            lng: 153.089480,
            address: "81 Noosa Dr (Corner Sunshine Beach Rd), Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["beer", "lunch", "dinner", "late_night"],
            known_for_bullets: ["Great beer range on tap", "Easy pub-style meals", "Good for groups + sport nights"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "medium",
            formality_level: 0,
            vibe_tags: ["casual", "groups", "beer"]
        },
        {
            name: "Coya",
            slug: "coya-noosa",
            category: "Restaurant",
            icon: "/icons/fancy_dinner.png",
            lat: -26.396860,            // 14 Sunshine Beach Rd
            lng: 153.090550,            // 14 Sunshine Beach Rd
            address: "1/14 Sunshine Beach Rd, Noosa Heads QLD 4567",
            manual_coords: true,
            is_active: true,
            best_for: ["lunch", "dinner", "date_night", "special_occasions", "drinks"],
            known_for_bullets: [
                "Modern Peruvian cuisine with vibrant flavours",
                "Fresh locally-sourced ingredients",
                "Great artisanal cocktails and wine selection"
            ],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["stylish", "romantic", "upscale", "casual_dining", "bar"]
        },
        {
            name: "Somedays Pizza",
            slug: "somedays-pizza-noosa",
            category: "Pizza",
            icon: "/icons/italian.png",
            lat: -26.397805,
            lng: 153.091274,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Noosa Junction (Sunshine Beach Rd), Noosa Heads QLD",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Pizza + casual drinks", "Great ‘no-fuss’ dinner pick", "Works well with friends"],
            price_risk: "medium",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 0,
            vibe_tags: ["casual", "groups"]
        },
        {
            name: "Sabrosa Dim Sum House",
            slug: "sabrosa-dim-sum-house-noosa",
            category: "Asian",
            icon: "/icons/asian.png",
            lat: -26.397805,
            lng: 153.091274,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Sunshine Beach Rd area, Noosa Heads QLD",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Dumplings + share plates", "Good for groups", "Great ‘something different’ pick"],
            price_risk: "medium",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["lively", "share-plates"]
        },
        {
            name: "Moto",
            slug: "moto-noosa",
            category: "Cafe / Bar",
            icon: "/icons/coffee.png",
            lat: -26.396846,
            lng: 153.087734,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Noosa Dr area, Noosa Heads QLD",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon"],
            known_for_bullets: ["Good coffee + easy bites", "Nice mid-day reset stop", "Good before heading back to the beach"],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "quick"]
        },
        {
            name: "Kaali Gourmet Indian",
            slug: "kaali-gourmet-indian-noosa",
            category: "Indian",
            icon: "/icons/asian.png",
            lat: -26.387074,
            lng: 153.091652,
            address: "Noosa Heads QLD (Hastings / nearby area)",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Proper curry night", "Good when you want hearty + filling", "Solid option away from seafood-heavy picks"],
            price_risk: "medium",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 0,
            vibe_tags: ["casual", "hearty"]
        },
        {
            name: "Piccolino",
            slug: "piccolino-noosa",
            category: "Italian",
            icon: "/icons/italian.png",
            lat: -26.396236,
            lng: 153.089460,
            address: "Noosa Heads QLD (Junction area)",
            is_active: true,
            best_for: ["dinner", "fancy_dinner"],
            known_for_bullets: ["Classic Italian comfort", "Good for a calm sit-down meal", "Works well for families too"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 1,
            vibe_tags: ["casual", "family"]
        },
        {
            name: "Halse Lodge (Restaurant & Bar)",
            slug: "halse-lodge-restaurant-bar-noosa",
            category: "Bar & Bistro",
            icon: "/icons/beer.png",
            lat: -26.388921,
            lng: 153.092357,
            coords_source: "address",
            coords_accuracy: "high",
            address: "2 Halse Ln, Noosa Heads QLD 4567",
            is_active: true,
            best_for: ["beer", "lunch", "dinner", "late_night"],
            known_for_bullets: ["Affordable meals near the action", "Easy drinks with a social vibe", "Good casual fallback when Hastings is packed"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "social", "budget-friendly"]
        },

        // ---- NOOSAVILLE / TEWANTIN (NOOSA AREA) ----
        {
            name: "Noosa Boathouse",
            slug: "noosa-boathouse-noosaville",
            category: "Waterfront Dining",
            icon: "/icons/wine.png",
            lat: -26.397617,
            lng: 153.061379,
            coords_source: "address",
            coords_accuracy: "high",
            address: "194 Gympie Terrace, Noosaville QLD 4566",
            is_active: true,
            best_for: ["breakfast", "coffee", "lunch", "afternoon", "dinner"],
            known_for_bullets: ["Waterfront views", "Great for long lunches", "Sunset drinks + easy share plates"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["views", "date", "sunset"],
            booking_likely: true
        },
        {
            name: "Gusto Riverfront Restaurant",
            slug: "gusto-riverfront-noosaville",
            category: "Modern Australian",
            icon: "/icons/fancy_dinner.png",
            lat: -26.397112,
            lng: 153.066400,
            coords_source: "address",
            coords_accuracy: "high",
            address: "257 Gympie Terrace, Noosaville QLD 4566",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner"],
            known_for_bullets: ["Riverfront sit-down dining", "Great for celebrations", "Good ‘proper dinner’ option in Noosaville"],
            price_risk: "high",
            walk_in_friendliness: "low",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["date", "special-occasion", "views"],
            booking_likely: true
        },
        {
            name: "Pucca (Noosaville)",
            slug: "pucca-noosaville",
            category: "Euro-Indian + Gin",
            icon: "/icons/wine.png",
            lat: -26.397540,
            lng: 153.064013,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Gympie Terrace area, Noosaville QLD 4566",
            is_active: true,
            best_for: ["dinner", "late_night"],
            known_for_bullets: ["Gin-forward bar energy", "Great for share plates", "Feels fun without being ‘clubby’"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["lively", "gin", "friends"],
            booking_likely: true
        },
        {
            name: "Noosa Waterfront Restaurant & Bar",
            slug: "noosa-waterfront-restaurant-bar",
            category: "Modern Australian",
            icon: "/icons/wine.png",
            lat: -26.398418,
            lng: 153.055178,
            coords_source: "address",
            coords_accuracy: "high",
            address: "142 Gympie Terrace, Noosaville QLD 4566",
            is_active: true,
            best_for: ["dinner", "fancy_dinner"],
            known_for_bullets: ["Riverside views", "Good for date nights", "Best when you want a quieter ‘nice dinner’"],
            price_risk: "high",
            walk_in_friendliness: "low",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["views", "date", "calm"],
            booking_likely: true
        },
        {
            name: "Noosa Yacht & Rowing Club",
            slug: "noosa-yacht-rowing-club",
            category: "Club / Bistro",
            icon: "/icons/beer.png",
            lat: -26.397540,
            lng: 153.064013,
            coords_source: "address",
            coords_accuracy: "high",
            address: "Gympie Terrace area, Noosaville QLD 4566",
            is_active: true,
            best_for: ["beer", "lunch", "dinner", "afternoon"],
            known_for_bullets: ["Straightforward club meals", "Good value + easy walk-ins", "Great for casual river sessions"],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "locals", "value"]
        },
        {
            name: "Lanai Noosa",
            slug: "lanai-noosa",
            category: "Seafood / Modern Australian",
            icon: "/icons/wine.png",
            lat: -26.398896,
            lng: 153.061808,
            coords_source: "address",
            coords_accuracy: "high",
            address: "1/201 Gympie Terrace, Noosaville QLD 4566",
            is_active: true,
            best_for: ["lunch", "afternoon", "dinner", "fancy_dinner"],
            known_for_bullets: ["Great riverfront vibe", "Perfect for long lunches", "A ‘nice’ dinner without Hastings chaos"],
            price_risk: "high",
            walk_in_friendliness: "medium",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["views", "date", "relaxed"],
            booking_likely: true
        },
        {
            name: "Lucio's Marina",
            slug: "lucios-marina-tewantin",
            category: "Italian",
            icon: "/icons/italian.png",
            lat: -26.394560,
            lng: 153.041659,
            coords_source: "address",
            coords_accuracy: "high",
            address: "2 Parkyn Court, Tewantin QLD 4565 (Noosa Marina)",
            is_active: true,
            best_for: ["lunch", "dinner", "fancy_dinner"],
            known_for_bullets: ["Marina views + proper Italian", "Great for celebrations", "Best booked on weekends"],
            price_risk: "high",
            walk_in_friendliness: "low",
            service_speed: "slow",
            formality_level: 2,
            vibe_tags: ["date", "special-occasion", "waterfront"],
            booking_likely: true
        },
        {
            name: "Kin Kin Hotel",
            slug: "kin-kin-hotel",
            category: "Pub / Bistro",
            icon: "/icons/beer.png",
            lat: -26.3009,
            lng: 152.8886,
            address: "57 Main St, Kin Kin QLD 4571",
            is_active: true,
            best_for: ["lunch", "dinner", "drinks", "groups"],
            known_for_bullets: [
                "Classic country pub meals",
                "Popular stop for hinterland day trips",
                "Very walk-in friendly"
            ],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "country", "groups", "beer"]
        },

        {
            name: "The Doonan",
            slug: "the-doonan",
            category: "Pub / Bistro",
            icon: "/icons/beer.png",
            lat: -26.4157,
            lng: 152.9956,
            address: "567 Weyba Creek Rd, Doonan QLD 4562",
            is_active: true,
            best_for: ["lunch", "dinner", "drinks", "families"],
            known_for_bullets: [
                "Large beer garden",
                "Good for families and groups",
                "Reliable pub-style menu"
            ],
            price_risk: "medium",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "families", "beer_garden"]
        },

        {
            name: "Spirit House",
            slug: "spirit-house",
            category: "Asian Fine Dining",
            icon: "/icons/fancy_dinner.png",
            lat: -26.4936,
            lng: 152.9612,
            address: "20 Ninderry Rd, Yandina QLD 4561",
            is_active: true,
            best_for: ["dinner", "special_occasion", "date"],
            known_for_bullets: [
                "Iconic Southeast Asian fine dining",
                "Highly regarded destination restaurant",
                "Garden setting"
            ],
            price_risk: "high",
            walk_in_friendliness: "low",
            service_speed: "slow",
            formality_level: 3,
            vibe_tags: ["upmarket", "destination", "special"]
        },

        {
            name: "China Diner",
            slug: "china-diner-noosa",
            category: "Asian Fusion",
            icon: "/icons/casual_dining.png",
            lat: -26.3948,
            lng: 153.0904,
            address: "Noosa Junction QLD 4567",
            is_active: true,
            best_for: ["lunch", "dinner", "groups"],
            known_for_bullets: [
                "Modern Asian fusion menu",
                "Good for sharing plates",
                "Popular Junction spot"
            ],
            price_risk: "medium",
            walk_in_friendliness: "medium",
            service_speed: "medium",
            formality_level: 1,
            vibe_tags: ["social", "modern", "asian"]
        },

        {
            name: "Nisa Thai",
            slug: "nisa-thai-noosa",
            category: "Thai",
            icon: "/icons/asian.png",
            lat: -26.3951,
            lng: 153.0901,
            address: "Noosa Junction QLD 4567",
            is_active: true,
            best_for: ["dinner", "takeaway", "casual_dinner"],
            known_for_bullets: [
                "Classic Thai favourites",
                "Good value portions",
                "Reliable takeaway option"
            ],
            price_risk: "low",
            walk_in_friendliness: "high",
            service_speed: "fast",
            formality_level: 0,
            vibe_tags: ["casual", "takeaway", "thai"]
        }

    ],
};
